name: Production Deploy

on:
  push:
    branches: [ master ]
#  release:
#    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ["prod"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Key for ${{ matrix.server.name }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update known_hosts for ${{ matrix.server }}
        run: |
          mkdir -p ~/.ssh
          HOST=${{ fromJson(secrets.PROD_CONFIG)[matrix.server] }}
          PORT=${{ secrets.SSH_PORT }}
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts

      - name: Run deploy_prod.sh on server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ fromJson(secrets.PROD_CONFIG)[matrix.server] }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "
          cd /var/www/ts-wms &&
          git checkout main &&
          git pull origin main --tags &&
          bash ./deploy_prod.sh
          "
